// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Ic1KfkMu3njN4KXM1kg5xK8CSKrKPEc',
    appId: '1:645631197921:web:b45f337066785bcf512da0',
    messagingSenderId: '645631197921',
    projectId: 'fitness-408b7',
    authDomain: 'fitness-408b7.firebaseapp.com',
    storageBucket: 'fitness-408b7.appspot.com',
    measurementId: 'G-43E1Y0R53J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzV6xMtOhrLlPC64aua73jhzmLMj377MM',
    appId: '1:645631197921:android:2a349014312a1de5512da0',
    messagingSenderId: '645631197921',
    projectId: 'fitness-408b7',
    storageBucket: 'fitness-408b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdfpEE8nS0QvSz-GanLklJdErDQ595bps',
    appId: '1:645631197921:ios:ce9ce8fa27a683af512da0',
    messagingSenderId: '645631197921',
    projectId: 'fitness-408b7',
    storageBucket: 'fitness-408b7.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdfpEE8nS0QvSz-GanLklJdErDQ595bps',
    appId: '1:645631197921:ios:ce9ce8fa27a683af512da0',
    messagingSenderId: '645631197921',
    projectId: 'fitness-408b7',
    storageBucket: 'fitness-408b7.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Ic1KfkMu3njN4KXM1kg5xK8CSKrKPEc',
    appId: '1:645631197921:web:215e4882db066705512da0',
    messagingSenderId: '645631197921',
    projectId: 'fitness-408b7',
    authDomain: 'fitness-408b7.firebaseapp.com',
    storageBucket: 'fitness-408b7.appspot.com',
    measurementId: 'G-ND107NR0JC',
  );

}